### ISSUE TITLE
Make the dashboard sidebar responsive for smaller screens

### ISSUE THREAD

**Issue by devkiran** [boxyhq/saas-starter-kit#202]
- It should be expanded when the user clicks on the hamburger icon
- It should be collapsed when the user clicks on the close icon

**Comment by shartrooper** [comment]
Hello,  I may be able to take this issue and check this one to implement responsiveness.

**Comment by shartrooper** [comment]
https://github.com/boxyhq/saas-starter-kit/assets/21326996/347410ff-044c-4dd7-b624-2f1f70995967

@devkiran 
This is the WIP of responsive sidebar im working on a local branch I made (I'd have pushed it and open a draft PR to show the progress but since I dont have permissions to publish, Ill comment the updates here).
- Note that it only toggles the sidebar visibility in screens below 1024 px.
- It closes by clicking outside container aswell, except on Navbar.
- The sidebar have to be removed from the document flow in order to avoid taking up another component's space.
- Im not sure what to do with the "close icon" you mention. It closes after clicking the hamburger aswell, should the hamburger icon be shifted by a close icon while opened? 
Im open to any suggestions.

**Comment by devkiran** [comment]
Please fork the repo and make a PR with your changes. You can leave the close button for now. A few things to note:

- Increase the width of the sidebar so that it covers the 80% of the screen.
- On smaller screen, remove the space on the left so that content is not pushed to the right.
